import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const helvetica = localFont({
  src: [
    {
      path: './fonts/helvetica/helvetica-regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/helvetica/helvetica-bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${helvetica.variable} font-sans`}>{children}</body>
    </html>
  );
}
